item_id:
  type: integer
item_name:
  type: string
item_label:
  type: string
chart_of_account_id:
  type: integer
chart_of_account_name:
  type: string
require_expiry_date:
  type: string
require_production_number:
  type: string
unit:
  type: string
converter:
  type: integer
quantity:
  type: integer
allocation_id:
  type: integer
allocation_name:
  type: string
notes:
  type: string
more:
  type: boolean